### ISSUE TITLE
just another question about the semicolon

### ISSUE THREAD

**Issue by Becca-Saunders** [Becca-Saunders/modularity-mindfulness#3]
Hello! I was able to get my difference percentage down but could I get more clarification about where the semi colon is supposed to go?  

I tried to change all of them to semi colons but then more issues popped up.

<img width="647" alt="Screen Shot 2021-09-29 at 5 49 27 PM" src="https://user-images.githubusercontent.com/77293037/135353571-c4d65c16-c9c2-4d6c-9117-0cd54146c255.png">
 

@wendywarren

**Comment by wendywarren** [comment]
Hi @Becca-Saunders!

For example, you would want the lines changed to:
`@-moz-viewport { width: device-width; scale:1; }`

Then continue for all lines in the screenshot above. This will bring up other issues in markbot for empty lines further down in your css but the errors are direct and tell you which lines to remove to fix.

How are things going with spacing?

Thanks,
Wendy

**Comment by Becca-Saunders** [comment]
> Hi @Becca-Saunders!
> 
> For example, you would want the lines changed to: `@-moz-viewport { width: device-width; scale:1; }`
> 
> Then continue for all lines in the screenshot above. This will bring up other issues in markbot for empty lines further down in your css but the errors are direct and tell you which lines to remove to fix.
> 
> How are things going with spacing?
> 
> Thanks, Wendy

Hello! I was able to submit this week's assignment! thanks for the help, I really appreciate it. 
I might make a git hub message about last week assignment, as I am still having issues with it. Would I still be able to submit? I know it would probably be marked late but thats okay. Better late than never.

**Comment by wendywarren** [comment]
Hi @Becca-Saunders!

Not a problem to submit last weeks assignment. I will look into how things are marked late. To my knowledge it shouldn't impact your grade but I'll look into this. 

Good luck and let me know if you have any questions.

Thanks,
Wendy
